// note用
export default {
  created() {
    console.log("start notes.js from mixins. OUR_THEME=" + this.OUR_THEME);
  },
  data() {
    return {
      OUR_THEME: "this is global theme",
      OUR_THEME_PATH: "/themesdtl",
      OUR_THEMES: [
        {
          id: "001",
          checked: false,
          catg: "Env",
          title: "VScode＆Vueでhtmlタグの補完が出来るように",
          words: "Veturに加えてvlsインストールと補完設定が必要",
          path: "",
        },
        {
            id: "002",
            checked: false,
            catg: "Env",
            title: "Git commit時の自動Buildを回避する",
            words: "commit時にBuildが走って結果失敗する",
            path: "",
        },
        {
            id: "003",
            checked: false,
            catg: "Env",
            title: "Git環境について",
            words: "中央（リモート）とローカル（開発）と本番と",
            path: "",
        },
        {
          id: "051",
          checked: false,
          catg: "JavaScript",
          title: "jQueryの使用方法を整理",
          words: "Vue内でのjQuery使用について",
          path: "/themesdtl?catg=jQuery",
        },
        {
          id: "052",
          checked: false,
          catg: "JavaScript",
          title: "クラス・オブジェクトの生成と使用",
          words: "各コンポーネント＆グローバルで使用したい時",
          path: "/themesdtl?catg=jQuery",
        },
        {
            id: "101",
            checked: false,
            catg: "Vue",
            title: "Vueのライフサイクルフックを整理",
            words: "Vue.jsにおけるライフサイクルフックイベントを整理",
            path: "",
        },
        {
            id: "102",
            checked: false,
            catg: "Vue",
            title: "v-ifで複数条件を処理したいとき",
            words: "v-ifでは複数条件を処理するためにcomputedを使う",
            path: "",
        },
        {
            id: "103",
            checked: false,
            catg: "Vue",
            title: "リストをフィルタリングする",
            words: "条件指定によるフィルタリングにcomputedを使う",
            path: "",
        },
        {
            id: "103",
            checked: false,
            catg: "Vue",
            title: "computedへ引数を渡したいとき",
            words: "computedにはそのままでは引数を渡すことが出来ない",
            path: "",
        },
        {
          id: "104",
          checked: false,
          catg: "Vue",
          title: "共通定義(mixin)の使用方法",
          words: "mixinによる共通定数の定義と使用方法",
          path: "",
        },
        {
          id: "105",
          checked: false,
          catg: "Vue",
          title: "共通関数(mixin)の使用方法",
          words: "mixinによる共通関数の定義と使用方法",
          path: "",
        },
        {
          id: "106",
          checked: false,
          catg: "Vue",
          title: "Vuexによる値の保持",
          words: "Vuexに値を保持",
          path: "",
        },
        {
          id: "107",
          checked: false,
          catg: "Vue",
          title: "VuexとLocalStorageの使い分け",
          words: "VuexとLocalStorageで永続的な値保持を",
          path: "",
        },
        {
          id: "108",
          checked: false,
          catg: "Vue",
          title: "VuexとAjaxの組み合わせ",
          words: "Ajaxで取得してVuexで保持",
          path: "",
        },
        {
          id: "201",
          checked: false,
          catg: "Data",
          title: "データ保持について",
          words: "LocalStorage or Database",
          path: "/themesdtl?catg=Data",
        },
        {
          id: "202",
          checked: false,
          catg: "LocalStorage",
          title: "LocalStorageの使用",
          words: "LocalStorageの使用について",
          path: "/themesdtl?catg=Data",
        },
        {
          id: "211",
          checked: false,
          catg: "Database",
          title: "データベースの使用",
          words: "データベースの使用について",
          path: "/themesdtl?catg=Data",
        },
        {
          id: "301",
          checked: false,
          catg: "JSON",
          title: "JSONの整理",
          words: "JSON形式をパターン化",
          path: "/themesdtl?catg=Data",
        },
        {
            id: "311",
            checked: false,
            catg: "Ajax",
            title: "Ajax サーバ側",
            words: "PHPでの実装",
        },
        {
            id: "312",
            checked: false,
            catg: "Ajax",
            title: "Ajax サーバ側エラー対応",
            words: "エラー時のレスポンスについて",
        },
        {
            id: "313",
            checked: false,
            catg: "Ajax",
            title: "Ajax Vue側(axios)",
            words: "Axios使用方法の整理",
        },
        {
            id: "314",
            checked: false,
            catg: "Ajax",
            title: "Ajax Vue側(axios)エラー処理",
            words: "Ajaxエラー時の処理について",
        },
        {
            id: "321",
            checked: false,
            catg: "Ajax",
            title: "Ajaxの使用：取得",
            words: "サーバからJSONを取得",
        },
        {
            id: "322",
            checked: false,
            catg: "Ajax",
            title: "Ajaxの使用：複数レコード",
            words: "サーバからJSONでリストを取得",
            path: "/themesdtl?catg=Data",
        },
        {
          id: "323",
          checked: false,
          catg: "Ajax",
          title: "Ajaxの使用：処理依頼",
          words: "サーバに処理を依頼（登録など）",
          path: "/themesdtl?catg=Data",
        },
        {
          id: "324",
          checked: false,
          catg: "Ajax",
          title: "Ajaxの使用：アップロード",
          words: "サーバに複数データを送信",
          path: "/themesdtl?catg=Data",
        },
        {
          id: "401",
          checked: false,
          catg: "Basic",
          title: "CSSの優先順位を整理",
          words: "",
          path: "/themesdtl?catg=Basic",
        },
        {
          id: "402",
          checked: false,
          catg: "Basic",
          title: "全体共通のCSSを設定したい",
          words: "",
          path: "/themesdtl?catg=Basic",
        },
        {
          id: "403",
          checked: false,
          catg: "Basic",
          title: "iframeの高さ調節に手間取る",
          words: "",
          path: "/themesdtl?catg=Basic",
        },
        {
            id: "501",
            checked: true,
            catg: "Basic",
            title: "戻るボタンについて",
            words: "戻るを効率的に設定したい",
            path: "/themesdtl?catg=Basic",
        },
        {
          id: "502",
          checked: true,
          catg: "Basic",
          title: "戻った時にタブ位置を復元したい(BootVue)",
          words: "Vuexを使用",
          path: "/themesdtl?catg=Basic",
        },
        {
          id: "503",
          checked: false,
          catg: "Basic",
          title: "戻った時にカーソル位置を復元したい(BootVue)",
          words: "",
          path: "/themesdtl?catg=Basic",
        },
        {
          id: "504",
          checked: false,
          catg: "Basic",
          title: "戻った時にフォーム値を復元したい(BootVue)",
          words: "",
          path: "/themesdtl?catg=Basic",
        },
        {
          id: "701",
          checked: false,
          catg: "Rule",
          title: "フォルダ構成パターン",
          words: "プロジェクト毎のフォルダ構成を整理",
        },
        {
            id: "702",
            checked: false,
            catg: "Rule",
            title: "ネーミングルール",
            words: "ネーミングルールにより理解しやすい環境を",
        },
      ],
    };
  },
};
